version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=smopshop
      - MYSQL_USER=smopshop
      - MYSQL_PASSWORD=smopshop
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  smop-shop-backend:
    build: ./smop-shop-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    # environment:
    #   DATABASE_URL: 'jdbc:mysql://mysql:3306/smopshop'
    #   DATABASE_USERNAME: 'smopshop'
    #   DATABASE_PASSWORD: 'smopshop'

volumes:
  db_data:
