spring:
  application:
    name: smopshop
  datasource:
    url: jdbc:mysql://localhost:3306/smopshop
    username: smopshop
    password: smopshop
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  currency-rates:
    ttl-millis: 1000 * 60 * 60
